-- INSERT INTO note (idnote, titolo, categoria, autore, data, testo, anteprima) VALUES (0,'Algebra booleana','Informatica', 'tommaso.guizza', '2023-10-11',"L'algebra booleana è un elemento fondamentale nella matematica e nella logica, con applicazioni ubiquitarie nell'informatica, nell'elettronica digitale e nella programmazione. La sua importanza si estende dalla progettazione di circuiti digitali all'implementazione di algoritmi e alla scrittura di codice efficiente. La capacità di rappresentare e manipolare le operazioni logiche fondamentali in modo simbolico e la possibilità di semplificare espressioni complesse attraverso teoremi e regole la rendono una disciplina indispensabile nell'era digitale moderna.Le operazioni fondamentali in algebra booleana sono l'AND, l'OR e il NOT. L'operazione AND restituisce 1 solo se entrambi gli operandi sono 1, altrimenti restituisce 0. L'operazione OR restituisce 1 se almeno uno degli operandi è 1. L'operazione NOT restituisce l'opposto del suo operando. Queste operazioni forniscono gli strumenti per rappresentare e manipolare le operazioni logiche di base.", "L'algebra booleana è un elemento fondamentale nella matematica e nella logica, con applicazioni ubiquitarie nell'informatica...");
USE notesync;

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (1,'Linguaggio SQL', 'Informatica', 'tommaso.guizza', '2023-10-11', "SQL, che sta per 'Structured Query Language', è un linguaggio standardizzato per i database basati sul modello relazionale. È stato introdotto negli anni '70 e da allora è diventato il linguaggio di programmazione standard per le applicazioni di database. SQL non si limita alle semplici query che gli danno il nome: permette di creare, gestire e amministrare database. Le sue funzionalità includono la creazione e la modifica degli schemi di database, l'inserimento, la modifica e la gestione dei dati memorizzati, l'interrogazione dei dati memorizzati e la creazione e la gestione degli strumenti di controllo e accesso ai dati. SQL funziona come interfaccia per la comunicazione con un sistema di gestione di database relazionale (RDBMS). Il codice SQL può essere immesso ed eseguito direttamente da persone mediante un'interfaccia di testo, oppure può essere integrato in accessi API. SQL è basato sull'algebra relazionale, una teoria matematica per strutturare dati e calcolare i risultati delle query. Da queste fondamenta matematiche derivano molte delle caratteristiche di SQL come linguaggio di programmazione.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (2, 'Seconda Guerra Mondiale', 'Storia', 'guido.mosconi', '2023-10-11', "La Seconda Guerra Mondiale (1939-1945) è stata un conflitto globale che ha coinvolto nazioni di tutto il mondo. Scaturita dalle tensioni post-Prima Guerra Mondiale, iniziò con l'invasione tedesca della Polonia nel 1939. Presto, Germania, Italia e Giappone formarono l'Asse, mentre Francia, Regno Unito e successivamente l'Unione Sovietica si unirono agli Alleati. La Blitzkrieg tedesca portò alla rapida conquista di molte nazioni europee, ma la Battaglia d'Inghilterra nel 1940 segnò un punto di svolta. Nel 1941, la Germania invase l'Unione Sovietica. Nel Pacifico, il Giappone espandeva il suo dominio. L'attacco giapponese a Pearl Harbor nel 1941 coinvolse gli Stati Uniti. Le battaglie del Pacifico, come Midway, videro gli Alleati guadagnare terreno. L'Olocausto, genocidio nazista, testimoniò l'orrore umano. Dopo la svolta a Stalingrado nel 1942, l'Unione Sovietica contrattaccò, liberando l'Europa orientale. Lo sbarco in Normandia nel 1944 avviò l'offensiva alleata in Europa occidentale. La Germania si arrese nel maggio 1945. Nel Pacifico, gli Alleati avanzarono, ma l'uso delle bombe atomiche su Hiroshima e Nagasaki nel 1945 portò alla resa del Giappone. La guerra finì nel settembre 1945. Le conseguenze furono enormi: milioni di morti, distruzioni, ma anche la nascita delle Nazioni Unite.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (3, 'Trasformata di Fourier', 'Fisica', 'giulia.rosi', '2022-05-24', "La trasformata di Fourier è uno strumento matematico che converte una funzione (generalmente nel dominio del tempo) in una combinazione di onde sinusoidali di diverse frequenze. Essenzialmente, scompone un segnale complesso in componenti più semplici, consentendo di analizzare la sua composizione frequenziale. Questa trasformazione è utilizzata ampiamente in diverse discipline, come l'ingegneria, la fisica, la matematica e le scienze applicate, per l'analisi dei segnali e l'elaborazione delle immagini.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (4, 'Evoluzione delle lingue', 'Italiano', 'bruno.barreca', '2018-06-01', "Le lingue subiscono costanti trasformazioni nel tempo a causa di fattori come migrazioni, contatti tra culture, innovazioni tecnologiche e cambiamenti sociali. L'evoluzione delle lingue può includere l'emergere di nuovi dialetti, l'assorbimento di parole straniere e l'evoluzione della grammatica. Esistono molte teorie e approcci alla comprensione di come e perché le lingue cambiano nel corso del tempo, contribuendo alla diversità linguistica che osserviamo oggi.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (5, 'Teoria della relatività', 'Fisica', 'emiliana.bonacquisti', '2022-04-25', "Proposta da Albert Einstein all'inizio del XX secolo, la teoria della relatività si divide in due principali concetti: la relatività ristretta e la relatività generale. La relatività ristretta tratta della relazione tra spazio e tempo, sostenendo che la velocità della luce sia costante e che spazio e tempo siano relativi all'osservatore. La relatività generale spiega la gravità come una conseguenza della curvatura dello spazio-tempo causata dalla presenza di massa ed energia.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (6, 'La storia della stampa', 'Storia', 'paolo.tozzi', '2021-12-20', "La storia della stampa inizia con l'invenzione della stampa a caratteri mobili da parte di Johannes Gutenberg nel XV secolo, che ha rivoluzionato la diffusione delle idee e dei testi. La stampa ha permesso la produzione in massa di libri, consentendo la diffusione del sapere e contribuendo alla riforma religiosa, all'illuminismo e alla diffusione dell'istruzione in tutto il mondo.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (7, 'Mitologia greca e romana', 'Storia', 'paolo.tozzi', '2019-01-04', "La mitologia greca e romana racconta le storie degli dèi dell'Olimpo, eroi epici come Ercole e Ulisse, e creature fantastiche come i centauri o le sirene. Queste mitologie hanno influenzato profondamente l'arte, la letteratura, la filosofia e la cultura occidentale, offrendo anche una finestra sulla comprensione delle credenze e della società dell'antica Grecia e Roma.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (8, 'Genetica ed ereditarietà', 'Biologia', 'luca.casalini', '2020-03-18', "La genetica è lo studio dei geni, delle eredità e delle variazioni genetiche in organismi viventi. È stata una delle aree più rivoluzionarie delle scienze biologiche. Scoperte cruciali come la struttura del DNA nel 1953 da parte di James Watson e Francis Crick, oltre alle leggi di Mendel sull'ereditarietà, hanno svelato i meccanismi di trasmissione dei tratti ereditari attraverso le generazioni. La genetica ha rivoluzionato la medicina, l'agricoltura e la nostra comprensione della vita stessa, portando a nuove terapie, modificazioni genetiche e nuovi modi per affrontare malattie genetiche. La genetica molecolare ha aperto la strada alla biotecnologia, consentendo la produzione di farmaci, alimenti e materiali innovativi.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (9, 'Diritti Umani', 'Diritto', 'matteo.laghi', '2020-04-16', " L'apprendimento sui diritti umani e la giustizia sociale coinvolge la comprensione delle disparità sociali, delle lotte storiche e delle attuali sfide legate alla discriminazione, all'equità e alla difesa dei diritti fondamentali di tutti gli individui.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (10, 'Ambiente e Sostenibilità', 'Biologia', 'luca.casalini', '2020-05-02', "L'ambiente è fondamentale per la sopravvivenza umana. L'apprendimento sui cambiamenti climatici, la conservazione della biodiversità e le pratiche sostenibili è cruciale per affrontare le sfide globali come la crisi climatica.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (11, 'La Filosofia Dialettica di Hegel', 'Filosofia', 'giuseppe.termoli', '2019-10-25', "Georg Wilhelm Friedrich Hegel è stato un filosofo tedesco del XIX secolo, conosciuto per la sua influenza nel campo della filosofia, in particolare per la sua concezione della dialettica e per il suo sistema filosofico complesso. La sua opera più celebre è la Scienza della logica, in cui espone una visione della realtà basata su processi dialettici e sul concetto di sviluppo storico attraverso tesi, antitesi e sintesi.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (12, 'Motore Elettrico', 'Fisica', 'paola.luciani', '2022-01-08', "Il motore elettrico è un dispositivo che trasforma l'energia elettrica in energia meccanica, utilizzata in svariate applicazioni, dalla produzione industriale ai trasporti elettrici. Basato sul principio dell'interazione tra campi magnetici, il motore elettrico rappresenta un pilastro fondamentale nella tecnologia moderna.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (13, 'Giuseppe Verga', 'Italiano', 'agnese.lontani', '2023-11-03', "Giuseppe Verga è stato uno dei più grandi scrittori italiani del XIX secolo, celebre per il suo stile realista e le descrizioni vivide della vita in Sicilia. Le sue opere, tra cui I Malavoglia e Cavalleria Rusticana, sono considerate capolavori della letteratura italiana per la loro profonda rappresentazione dei valori, delle tensioni sociali e della vita delle classi popolari.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (14, 'Puzzle Geologico', 'Biologia', 'luca.casalini', '2019-06-01', "La deriva dei continenti è una teoria geologica che suggerisce che i continenti sulla Terra si sono mossi nel corso del tempo geologico. Proposta originariamente da Alfred Wegener nel primo XX secolo, questa teoria ha trovato conferme attraverso prove geologiche, paleontologiche e geofisiche, portando alla comprensione moderna della tettonica delle placche.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (15, 'Strutture Dati', 'Informatica', 'licia.giannetti', '2021-03-18', "Le strutture dati sono metodi organizzativi utilizzati per immagazzinare, gestire e manipolare dati in modo efficiente. Rappresentano un aspetto cruciale nell'informatica e nell'elaborazione delle informazioni, offrendo diversi modelli e algoritmi per l'accesso ottimale e la gestione dei dati in vari contesti applicativi.");

INSERT INTO note (idnote, titolo, categoria, autore, data, testo) VALUES (16, 'Costituzione Italiana', 'Diritto', 'matteo.laghi', '2021-09-29', "La Costituzione Italiana, adottata nel 1947, rappresenta il pilastro del sistema legale e politico della Repubblica Italiana. È un documento che stabilisce i principi fondamentali, i diritti dei cittadini, le istituzioni pubbliche e i valori su cui si basa la nazione.");

UPDATE notesync.note 
SET stato = 'approvato'
WHERE stato = 'da approvare';